cmake_minimum_required(VERSION 3.7)

set(SIMD_TEST OFF CACHE BOOL "" FORCE)
set(SIMD_SHARED OFF CACHE BOOL "" FORCE)
set(SIMD_GET_VERSION OFF CACHE BOOL "" FORCE)
set(SIMD_TOOLCHAIN ${CMAKE_CXX_COMPILER})
set(SIMD_INFO ${ADX_INFO} CACHE BOOL "" FORCE)
set(SIMD_SYNET OFF CACHE BOOL "" FORCE)
set(SIMD_INT8_DEBUG OFF CACHE BOOL "" FORCE)
set(SIMD_LIB "Simd")	
set(SIMD_PERF OFF CACHE BOOL "" FORCE)

set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR})

add_subdirectory(${ROOT_DIR}/3rd/Simd/prj/cmake 3rd/Simd)

include_directories(${ROOT_DIR}/3rd/Simd/src)
